app:
  safe_name: 'dataos_cli'
  product_safe_name: 'dataos'
auth:
  issuer_url: 'https://{{.DataOsFqdn}}/oidc'
  client_id: 'dataos_client'
  client_secret: 'ebd197502eca4e888ef0b5f384b47db3'
  redirect_url: 'https://127.0.0.1:32200/callback'
  listen_url: 'https://127.0.0.1:32200/'
  client_scope: 'openid profile groups email federated:id offline_access'
  tls_crt_file: '{{.DataOsConfigDir}}/bin/localhost.crt'
  tls_key_file: '{{.DataOsConfigDir}}/bin/localhost.key'
authz:
  heimdall_url: 'https://{{.DataOsFqdn}}/heimdall'
  authz_path: '/api/v1/authorize'
  users_path: '/api/v1/users'
  user_path: '/api/v1/users/%s'
  user_tags_path: '/api/v1/tags'
  user_tag_path: '/api/v1/tags/%s'
  token_path: '/api/v1/users/%s/tokens'
  tokens_path: '/api/v1/tokens'
  policies_path: '/api/v1/policies'
  policy_path: '/api/v1/policies/%s'
  secrets_path: '/api/v1/secrets'
  secret_path: '/api/v1/secrets/%s'
operate:
  helm_binary: '/usr/local/bin/helm'
run:
  fqdn: '{{.DataOsFqdn}}'
  resource_url: 'https://{{.DataOsFqdn}}'
  resource_base_path: '/poros/api/v1'
  resource_path: '/workspaces/%s/resources/%s/%s'
  resources_path: '/workspaces/%s/resources'
  cluster_resource_path: '/resources/%s/%s'
  cluster_resources_path: '/resources'
  cluster_resource_log_path: '/resources/%s/%s/log'
  cluster_resource_runtime_path: '/resources/%s/%s/runtime'
  resource_log_path: '/workspaces/%s/resources/%s/%s/log'
  resource_runtime_path: '/workspaces/%s/resources/%s/%s/runtime'
  resource_pod_path: '%s/pods/%s/%s'
  caretaker_url: 'https://{{.DataOsFqdn}}'
  caretaker_base_path: '/caretaker/api/v1'
  caretaker_base_path_v2: '/caretaker/api/v2'
  dataos_address_regexp: '(dataos([:A-Za-z0-9\-]*):\/\/)([A-Za-z0-9\-\_]+)'
  plutus_url: 'https://prime.tmdata.io/plutus/api/v1'
  peer_server_port: '8444'
  collation_url: 'https://{{.DataOsFqdn}}/collated'
  gateway_url_template: 'https://%s:7432'
depot:
  url: 'https://{{.DataOsFqdn}}/ds'
  base_path: '/api/v2'
  depot_path: '/depots/%s'
  depots_path: '/depots'
  collection_path: '/collections/%s'
  collections_path: '/collections'
  dataset_path: '/datasets/%s'
  datasets_path: '/datasets'
  version_path: '/metadata/%s'
  fields_path: '/fields'
  field_path: '/fields/%s'
  field_rename_path: '/rename'
  field_update_path: '/update'
  field_nullable_path: '/nullable/%s'
  snapshots_path: '/snapshots'
  snapshot_path: '/snapshots/%s'
  rollback_path: '/rollback/%s'
  metadata_path: '/metadata'
  properties_path: '/properties'
  partitions_path: '/partitions'
  resolver_path: '/resolve?address=%s'
themis:
  themis_admin_path: '/v1/admin/%s/%s'