name: Print Commit Usernames

on:
  push:
    branches:
      - main # or your default branch

jobs:
  print_usernames:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get commit usernames
      run: |
        echo "Fetching commit usernames..."
        # Get the list of commits
        commits=$(git log --format='%H' -n 10)  # Adjust the number as needed
        
        # Loop through each commit hash
        for commit in $commits
        do
          # Get the username for the commit
          username=$(git log --format='%an' -n 1 $commit)
          echo "Commit $commit was made by $username"
        done
