name: Check YAML Files and Changes

on:
  push:
    branches:
      - main # or your default branch

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List YAML files
      id: list_yaml_files
      run: |
        echo "Listing all YAML files..."
        find . -name "*.yaml" -o -name "*.yml" > all_yaml_files.txt
        cat all_yaml_files.txt

    - name: Check for YAML file changes in the last commit
      id: check_yaml_changes_last_commit
      run: |
        echo "Fetching commit details..."
        previous_commit=$(git rev-parse HEAD~1)
        current_commit=$(git rev-parse HEAD)
        echo "Previous commit: $previous_commit"
        echo "Current commit: $current_commit"

        echo "Listing changed YAML files between the previous and current commit..."
        changed_files=$(git diff --name-only $previous_commit $current_commit | grep -E '\.(yaml|yml)$')

        if [ -n "$changed_files" ]; then
          echo "Changed YAML files:"
          echo "$changed_files"
        else
          echo "No YAML files changed in the last commit."
        fi
